### ISSUE TITLE
Not working when having large height header

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/CollectionViewInScrollView#1]
i have a very large content height header then collection view , and it is not working 

find the below code 

<Grid RowDefinitions="500,*">

        <ctrls:GoodCollectionView
            x:Name="collectionView"
            Grid.Row="1"
            CustomHeader="myCustomHeader"
            ItemSizingStrategy="MeasureFirstItem"
            ItemsLayout="VerticalGrid, 3"
            ItemsSource="{Binding Images}"
            SecondContent="labelView">

            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Image
                        Margin="0"
                        HeightRequest="120"
                        HorizontalOptions="FillAndExpand"
                        Source="{Binding .}">
                        <Image.GestureRecognizers>
                            <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                        </Image.GestureRecognizers>
                    </Image>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </ctrls:GoodCollectionView>

        <StackLayout
            x:Name="myCustomHeader"
            Grid.Row="0"
            VerticalOptions="Start">

            <Label
                Padding="50"
                BackgroundColor="DeepSkyBlue"
                FontSize="Large"
                HorizontalTextAlignment="Center"
                Text="This is my HEADER Content!!!" />

            <StackLayout
                BackgroundColor="AliceBlue"
                HeightRequest="56"
                HorizontalOptions="FillAndExpand"
                Orientation="Horizontal">
                <Button
                    x:Name="btn1"
                    Clicked="btn1_Clicked"
                    HorizontalOptions="FillAndExpand"
                    Text="Tab1" />

                <Button
                    x:Name="btn2"
                    Clicked="btn2_Clicked"
                    HorizontalOptions="FillAndExpand"
                    Text="Tab2" />
            </StackLayout>
        </StackLayout>

        <Label
            x:Name="labelView"
            Padding="50"
            BackgroundColor="LightGoldenrodYellow"
            FontSize="Large"
            HorizontalTextAlignment="Center"
            IsVisible="False"
            Text="This is TAB2 Content !!!" />

    </Grid>

**Comment by luismts** [comment]
Man, for your implementation you need to adapt this example. It just an example.

Sorry, I'm going to close this.
