### ISSUE TITLE
Full Scroll

### ISSUE THREAD

**Issue by angelru** [luismts/CollectionViewInScrollView#2]
This running the sample, updating to XF 5.0 on a xiaomi mi6 and it does not work, it does full scroll

**Comment by luismts** [comment]
Dont use CollectionView within a ScrollView.

I wrote a blog post talking about it. You can see it here: 

- EN: [Don’t use CollectionView inside ScrollView in Xamarin.Forms](https://luismts.com/dont-use-collectionview-inside-scrollview/)
- ES: [No uses CollectionView dentro de un ScrollView en Xamarin.Forms](https://luismts.com/es/no-uses-collectionview-en-scrollview/)

**Comment by angelru** [comment]
I am using ctrls: GoodCollectionView
